### ISSUE TITLE
Long text not supported

### ISSUE THREAD

**Issue by manhpham90vn** [quanghoang0101/HPGradientLoading#2]
![Simulator Screen Shot - iPhone 6 - iOS 12 2 - 2019-05-02 at 15 08 04](https://user-images.githubusercontent.com/40340023/57063005-1c09d980-6cec-11e9-80cd-d5e4fae56a2c.png)

**Comment by quanghoang0101** [comment]
Thanks for your feedback!

**Comment by quanghoang0101** [comment]
@manhpham90vn It is available at 1.2.1 now
